INSERT INTO PUBLIC.USERS (ID, NAME, EMAIL, PHONE) VALUES (1, 'Joe Simmons', 'joe@email.com', '5551234567');
INSERT INTO PUBLIC.USERS (ID, NAME, EMAIL, PHONE) VALUES (2, 'Jane Smith', 'jane@email.com', '5557654321');

INSERT INTO PUBLIC.USER_MESSAGE_CATEGORY (USER_ID, MESSAGE_CATEGORY_ID) VALUES (1, 100001);
INSERT INTO PUBLIC.USER_MESSAGE_CATEGORY (USER_ID, MESSAGE_CATEGORY_ID) VALUES (2, 100001);
INSERT INTO PUBLIC.USER_MESSAGE_CATEGORY (USER_ID, MESSAGE_CATEGORY_ID) VALUES (2, 100002);

INSERT INTO PUBLIC.USER_NOTIFICATION_TYPE (USER_ID, NOTIFICATION_TYPE_ID) VALUES (1, 200001);
INSERT INTO PUBLIC.USER_NOTIFICATION_TYPE (USER_ID, NOTIFICATION_TYPE_ID) VALUES (1, 200003);
INSERT INTO PUBLIC.USER_NOTIFICATION_TYPE (USER_ID, NOTIFICATION_TYPE_ID) VALUES (2, 200001);
INSERT INTO PUBLIC.USER_NOTIFICATION_TYPE (USER_ID, NOTIFICATION_TYPE_ID) VALUES (2, 200002);
INSERT INTO PUBLIC.USER_NOTIFICATION_TYPE (USER_ID, NOTIFICATION_TYPE_ID) VALUES (2, 200003);
